//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : MarketData
	/// Data Source    : MarketData
	/// Server Version : 3.24.0
	/// </summary>
	public partial class MarketDataDB : LinqToDB.Data.DataConnection
	{
		public ITable<EveItemName>             EveItemNames            { get { return this.GetTable<EveItemName>(); } }
		public ITable<EveItemNameOld20211126>  EveItemNameOld20211126  { get { return this.GetTable<EveItemNameOld20211126>(); } }
		public ITable<EveItemNameOld202111261> EveItemNameOld202111261 { get { return this.GetTable<EveItemNameOld202111261>(); } }
		public ITable<EveMarketGroup>          EveMarketGroups         { get { return this.GetTable<EveMarketGroup>(); } }
		public ITable<EveRegion>               EveRegions              { get { return this.GetTable<EveRegion>(); } }
		public ITable<EveTypeGroup>            EveTypeGroups           { get { return this.GetTable<EveTypeGroup>(); } }

		public MarketDataDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MarketDataDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MarketDataDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MarketDataDB(LinqToDbConnectionOptions<MarketDataDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("eve_item_name")]
	public partial class EveItemName
	{
		[Column("id"),      Nullable] public long?  Id     { get; set; } // integer
		[Column("item_id"), Nullable] public long?  ItemId { get; set; } // integer
		[Column("type"),    Nullable] public long?  Type   { get; set; } // integer
		[Column("en_name"), Nullable] public string EnName { get; set; } // text(255)
		[Column("zh_name"), Nullable] public string ZhName { get; set; } // text(255)
	}

	[Table("_eve_item_name_old_20211126")]
	public partial class EveItemNameOld20211126
	{
		[Column("id"),      Nullable] public long?  Id     { get; set; } // integer
		[Column("item_id"), Nullable] public long?  ItemId { get; set; } // integer
		[Column("type"),    Nullable] public string Type   { get; set; } // text(255)
		[Column("en_name"), Nullable] public string EnName { get; set; } // text(255)
		[Column("zh_name"), Nullable] public string ZhName { get; set; } // text(255)
	}

	[Table("_eve_item_name_old_20211126_1")]
	public partial class EveItemNameOld202111261
	{
		[Column("id"),      Nullable] public long?   Id     { get; set; } // integer
		[Column("item_id"), Nullable] public long?   ItemId { get; set; } // integer
		[Column("type"),    Nullable] public double? Type   { get; set; } // real
		[Column("en_name"), Nullable] public string  EnName { get; set; } // text(255)
		[Column("zh_name"), Nullable] public string  ZhName { get; set; } // text(255)
	}

	[Table("eve_market_groups")]
	public partial class EveMarketGroup
	{
		[Column("id"),              Nullable] public long?  Id            { get; set; } // integer
		[Column("parent_group_id"), Nullable] public long?  ParentGroupId { get; set; } // integer
		[Column("name"),            Nullable] public string Name          { get; set; } // text(255)
		[Column("name_zh"),         Nullable] public string NameZh        { get; set; } // text(255)
		[Column("icon_id"),         Nullable] public long?  IconId        { get; set; } // integer
		[Column("has_type"),        Nullable] public string HasType       { get; set; } // text(255)
	}

	[Table("eve_region")]
	public partial class EveRegion
	{
		[Column("id"),   PrimaryKey,  NotNull] public long   Id   { get; set; } // integer
		[Column("name"),    Nullable         ] public string Name { get; set; } // text(max)
	}

	[Table("eve_type_group")]
	public partial class EveTypeGroup
	{
		[Column("id"),       Nullable] public long? Id      { get; set; } // integer
		[Column("type_id"),  Nullable] public long? TypeId  { get; set; } // integer
		[Column("group_id"), Nullable] public long? GroupId { get; set; } // integer
	}

	public static partial class TableExtensions
	{
		public static EveRegion Find(this ITable<EveRegion> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
